In [17]:
import numpy as np

In [18]:
### 1 
a = np.arange(12, 24) 
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [19]:
### 2
a1 = a.reshape(3, 4)
a2 = a.reshape(2, 6)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(1, 12)
print ('a1: ',a1)
print ('a2: ',a2)
print ('a3: ',a3)
print ('a4: ',a4)
print ('a5: ',a5)

a1:  [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a2:  [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
a3:  [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a4:  [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a5:  [[12 13 14 15 16 17 18 19 20 21 22 23]]


In [20]:
### 3-4 -  массив Numpy, состоящий из одного столбца и 12 строк, нельзя назвать одномерным

a1 = a.reshape(3, -1)
a2 = a.reshape(2, -1)
a3 = a.reshape(4, -1)
a4 = a.reshape(-1, 2)
a5 = a.reshape(-1, 12)
print ('a1: ',a1)
print ('a2: ',a2)
print ('a3: ',a3)
print ('a4: ',a4)
print ('a5: ',a5)

a1:  [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a2:  [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
a3:  [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a4:  [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a5:  [[12 13 14 15 16 17 18 19 20 21 22 23]]


In [21]:
### 5
a = np.random.randn(3, 4)
a

array([[ 1.09705774, -0.31469762, -0.86221975,  0.13871927],
       [-0.34099889, -0.6387598 , -0.40263798, -0.77888753],
       [ 0.17718625, -1.79771999, -0.20663767, -0.01994667]])

In [23]:
print(b.size)
b=a.flatten()
print(b.size)
b

12
12


array([ 1.09705774, -0.31469762, -0.86221975,  0.13871927, -0.34099889,
       -0.6387598 , -0.40263798, -0.77888753,  0.17718625, -1.79771999,
       -0.20663767, -0.01994667])

In [24]:
b

array([ 1.09705774, -0.31469762, -0.86221975,  0.13871927, -0.34099889,
       -0.6387598 , -0.40263798, -0.77888753,  0.17718625, -1.79771999,
       -0.20663767, -0.01994667])

In [25]:
### 6
a=np.arange(20, 0, -2)

In [26]:
a ### одномерный массив

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [27]:
### 7
b=np.arange(20, 1, -2).reshape(1,10)

In [28]:
b  ### двумерный массив

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [29]:
### 8
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [31]:
b = np.zeros((3, 2))+1
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
v = np.row_stack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
v = v.size
v

10

In [42]:
### 9
a=np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
A=a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
At=A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [44]:
B = np.dot(A, At)
B ### Размер 4*4

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [46]:
Binv = np.linalg.inv(B)

LinAlgError: Singular matrix

In [48]:
### 10
a = np.random.seed(42)

In [51]:
### 11
c=np.random.randint(0, 16,16)
c

array([11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14])

In [55]:
### 12
C=c.reshape(4,4)
C

array([[11,  9,  5, 12],
       [11,  8,  0, 10],
       [10, 14,  9, 15],
       [11, 11, 15, 14]])

In [56]:
D=B+C*10
D

array([[115, 104,  73, 152],
       [124, 130,  86, 222],
       [123, 226, 239, 362],
       [142, 232, 362, 442]])

In [57]:
determinant=np.linalg.det(D)
determinant

62650800.0

In [59]:
rang = np.linalg.matrix_rank(D)
rang

4

In [60]:
D_inv=np.linalg.inv(D)
D_inv

array([[ 0.01886552, -0.00325327, -0.01147599,  0.00454519],
       [ 0.01683203, -0.02439777,  0.02559361, -0.01449559],
       [ 0.01273886, -0.01565599, -0.00270994,  0.00570208],
       [-0.02532897,  0.02667356, -0.00752744,  0.00374073]])

In [61]:
13
D_inv=np.where(D_inv<0, 0,1)
D_inv

array([[1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 1]])

In [63]:
E=np.where(D_inv==1, B, C)
E

array([[  5,   9,   5,  32],
       [ 14,   8,  86,  10],
       [ 23,  14,   9, 212],
       [ 11, 122,  15, 302]])